### ISSUE TITLE
text file isn't running after pip is installed?

### ISSUE THREAD

**Issue by luxemedia** [hamzaaitbrik/RedditDMBot#1]

**Comment by hamzaaitbrik** [comment]
Hello, can you link the error that gets returned upon executing the `pip3 install -r r.txt` command?

**Comment by hamzaaitbrik** [comment]
My bet is that you're having an error when trying to install modules that are already installed on your machine. In the `r.txt` file, I have listed all the modules that the bot will need to run, including the ones that come preinstalled with Python3 package. I edited the `r.txt` file, could you re-execute the command and let me know how it goes?

**Comment by hamzaaitbrik** [comment]
I will close this issue since I have tested the new code in my local machine as well as two remote servers. Feel free to open another issue if you find some.
