### ISSUE TITLE
its not sending dm

### ISSUE THREAD

**Issue by fwtih** [hamzaaitbrik/RedditDMBot#2]
ERROR! An exception occured. Retrying...

**Comment by TKObyKC** [comment]
Yah mate I'm running into the same issue

**Comment by hamzaaitbrik** [comment]
@fwtih @TKObyKC I am aware of the situation. I have been contacted by someone on Discord and I have been testing the bot for the last week or so.. I came up with a solution, but it uses JavaScriptDOM; it's not as efficient as using Selenium for the whole project.. I will be pushing the code for the solution and closing this issue when doing so. Bear with me, I'm doing my best with what little time I have..

**Comment by TKObyKC** [comment]
thanks mate. really appreciate all the time and effort you put into your work.

**Comment by hamzaaitbrik** [comment]
@fwtih @TKObyKC fixed. feel free to test it and let me know how it goes, I won't close this issue until you validate that it works for you as well.

**Comment by hamzaaitbrik** [comment]
@fwtih @TKObyKC I have had people confirm that it's working, I have also tested it on my Linux and Windows machines. I will close this issue as I think it is solved. If another issue may arise, please don't hesitate to open one.
