### ISSUE TITLE
errors at the point of logging in

### ISSUE THREAD

**Issue by THartyMBA** [hamzaaitbrik/RedditDMBot#4]
When running py.py, The bot pulls up a chrome browser and enters the username and password successfully. Reddit initially says that the login was successful before going to a splash page saying something went wrong so of course sending the message to the list of usernames begins to fail after that. Do you think this is an update with reddit trying to prevent bots or is it something wrong on my end?

**Comment by THartyMBA** [comment]
I ended up getting past the login issues by making this change: REDDIT_LOGIN_PAGE_URL = r'https://www.reddit.com/login' ; but now I can't get this to work and can't seem to figure out a change that makes it work: MESSAGE_URL = r'https://chat.reddit.com/user'

**Comment by Towpe94** [comment]
> When running py.py, The bot pulls up a chrome browser and enters the username and password successfully. Reddit initially says that the login was successful before going to a splash page saying something went wrong so of course sending the message to the list of usernames begins to fail after that. Do you think this is an update with reddit trying to prevent bots or is it something wrong on my end?

I have the exact same problem, let me know if you figured something out please

**Comment by hamzaaitbrik** [comment]
@THartyMBA @Towpe94 I will start working on this project again in a couple of weeks from now. I have no idea what's the situation like; I haven't run it in months.

**Comment by hamzaaitbrik** [comment]
@THartyMBA @Towpe94

Fixed. Could you please review it?

**Comment by hamzaaitbrik** [comment]
Fixed.
