### ISSUE TITLE
Message sending only if the user exist in chat list

### ISSUE THREAD

**Issue by the0therguy** [hamzaaitbrik/RedditDMBot#5]
He I attached my terminal screenshot
![terminal](https://github.com/hamzaaitbrik/RedditDMBot/assets/61143917/ae337464-5aa8-4360-9fa0-7c6e43adb4f5)
Here if you look closely I the bot says that he texted the 3 users.
![image](https://github.com/hamzaaitbrik/RedditDMBot/assets/61143917/f4f3cf7b-ed3c-4c0c-86cd-27e6e9453999)
I attached my chat window. It texted the only who is already in my chat list.
Thank you.

**Comment by hamzaaitbrik** [comment]
Hello. I have abandoned this project for some time now due to being busy with some personal matters. I am surprised the bot still works. I will work on it in the upcoming weeks and maybe build something more efficient that this. Thanks for bringing this issue to my attention.

**Comment by hamzaaitbrik** [comment]
Fixed. Could you please review it?

**Comment by the0therguy** [comment]
Ok I am reviewing it.

**Comment by hamzaaitbrik** [comment]
> Ok I am reviewing it. there is still an error. ![image](https://private-user-images.githubusercontent.com/61143917/290414773-b3787f78-3850-4fde-9edc-869be24e54f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Nzc1MTIsIm5iZiI6MTcwMjU3NzIxMiwicGF0aCI6Ii82MTE0MzkxNy8yOTA0MTQ3NzMtYjM3ODdmNzgtMzg1MC00ZmRlLTllZGMtODY5YmUyNGU1NGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE4MDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MGZkMTNjMDYxNDM4ODEwZWU4ZjhmYTVjMTE3YTM3NDdiYjQ1Y2RhYWRlMjYyYTFjOGQ1ZWU5MjRhMzUzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejYgvWkqck9Sld38WqICQPZc80qoaKHHmorChy2W4M0)

I see, it works okay for me. You mind linking the whole error for me to examine?

I am thinking of changing the whole logic of the bot these days tho, maybe make something new..make sure you have this project starred and watched so that you get the latest updates.
